name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Test
    uses: jontze/.workflows/.github/workflows/test.yml@main
    with:
      build: true
      unit-test: true
