name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Test
    uses: jontze/.workflows/.github/workflows/rust_test.yaml@main
    with:
      build: true
      unit-tests: true

  next:
    name: Release
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: jontze/.workflows/.github/workflows/rust_release.yaml@main
